name: maven_build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Core
      run: |
        cd core
        mvn install
        cd ..;
    - name: Build IO
      run: |
        cd file-io
        mvn install
        cd ..;
